import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Register.module.css';
import { Inter } from '@next/font/google';
import Button from '@/components/Button';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] });

function EmailConfirm() {
    const router = useRouter();

    function handleClick() {
        router.push('/login');
    }
    return (
        <>
            <Head>
                <title>Password recovery</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={[inter.className, styles.main].join(' ')}>
                <Image
                    className={styles.img}
                    src="/logo.png"
                    alt="Kadence Logo"
                    width={380}
                    height={200}
                    priority
                />
                <h4>Check the provided email address for the recovery link!</h4>
                <Button onClick={handleClick}>Login Page</Button>
            </main>
        </>
    );
}

export default EmailConfirm;
