import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/Register.module.css';
import Textbox from '@/components/Textbox';
import Button from '@/components/Button';
import { Inter } from '@next/font/google';
import { useRouter } from 'next/router';

import NetworkAPI from '@/lib/networkAPI';

const inter = Inter({ subsets: ['latin'] });

export default function Login() {
    const router = useRouter();

    async function handleSubmit(e) {
        const form = e.target;
        const { email } = form;
        e.preventDefault();

        // Send Request
        try {
            const data = await NetworkAPI.post('/api/users/forgottenPass', {
                email: email.value,
            });
            if (data) {
                console.log('Success!');
                router.push('/emailConfirm');
            }
        } catch (err) {
            console.log('Error: ', err.status, err);
        }
    }

    return (
        <>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={[inter.className, styles.main].join(' ')}>
                <Image
                    className={styles.img}
                    src="/logo.png"
                    alt="Kadence Logo"
                    width={380}
                    height={200}
                    priority
                />
                <form
                    className={styles.form}
                    method="POST"
                    action="/api/users/forgottenPass"
                    onSubmit={handleSubmit}
                >
                    {' '}
                    <h4>
                        Please enter the email address associated with the
                        account.
                    </h4>
                    <Textbox
                        name="email"
                        placeholder="Email Address"
                        required
                    />
                    <Link className={styles.note} href="/login">
                        {'Remember your password? Login here!'}
                    </Link>
                    <Button type="submit">Send Email!</Button>
                </form>
            </main>
        </>
    );
}
