import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/Register.module.css';
import Textbox from '@/components/Textbox';
import Button from '@/components/Button';
import { Inter } from '@next/font/google';
import { useRouter } from 'next/router';
import { userService } from '@/services/user.services';

import NetworkAPI from '@/lib/networkAPI';

const inter = Inter({ subsets: ['latin'] });

export default function Login() {
    const router = useRouter();

    function handleSubmit(e) {
        const form = e.target;
        const { username, enteredPW } = form;
        e.preventDefault();
        
        return userService.login(username, enteredPW)
            .then(() => {
                console.log("returning to the page")
                // get return url from query parameters or default to '/'
                const returnUrl = '/home';
                router.push(returnUrl);
            })
            .catch(error => {
                setError('apiError', { message: error });
            });
    }

    return (
        <>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={[inter.className, styles.main].join(' ')}>
                <Image
                    className={styles.img}
                    src="/logo.png"
                    alt="Kadence Logo"
                    width={380}
                    height={200}
                    priority
                />
                <form
                    className={styles.form}
                    method="POST"
                    action="/api/users/login"
                    onSubmit={handleSubmit}
                >
                    <Textbox name="username" placeholder="Username" required />
                    <Textbox
                        name="enteredPW"
                        placeholder="Password"
                        type="password"
                        required
                    />
                    <Link className={styles.note} href="/register">
                        {"Don't have an account? Register here!"}
                    </Link>
                    <Button type="submit">Login</Button>
                </form>
            </main>
        </>
    );
}
