import * as React from 'react';
import Head from 'next/head';
import styles from '@/styles/Platform.module.css';
import Image from 'next/image';
import { signIn, useSession, signOut } from 'next-auth/react';
import { useRouter } from 'next/router';
import { Dialog } from '@capacitor/dialog';
import { Box, Button, Stack } from '@mui/material/';
import NetworkAPI from '@/lib/networkAPI';

export default function Platform() {
    const router = useRouter();
    const { data: session } = useSession();

    async function handleSpotify() {
        // This is for changing the platform (logout of one)
        if (session) {
            signOut();
        }
        
        signIn();
        const newPlatformData = {
            username: localStorage.getItem('username'),
            musicPlatforms: "Spotify",
        };
        
        try {
            await NetworkAPI.patch('/api/users/update', newPlatformData);
            router.push('/profile');
        } catch (err) {
            Dialog.alert({
                title: 'Error',
                message: `An error occurred while submitting your data: ${err.message}.`,
            });
        }
    }

    return (
        <>
            <Head>
                <title>Select Platform</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Box>
                    <Stack spacing={2} alignItems="center">
                        <Image
                            src="/Spotify.jpg"
                            alt="Spotify Logo"
                            width="300"
                            height="150"
                            className={styles.platformImage}
                            priority
                        />
                        <Button variant="contained" onClick={handleSpotify}>
                            Connect to Spotify!
                        </Button>
                        <br />
                        <Image
                            src="/apple-music.jpg"
                            alt="Apple Music Logo"
                            width="300"
                            height="150"
                            className={styles.platformImage}
                            priority
                        />
                        <Button variant="contained" onClick={handleSpotify}>
                            Connect to Apple Music!
                        </Button>
                    </Stack>
                </Box>
            </main>
        </>
    );
}