import Head from 'next/head';
import styles from '@/styles/Platform.module.css';
import Image from 'next/image';
import { signIn } from 'next-auth/react';
import { useRouter } from 'next/router';
import { Box, Button, Stack } from '@mui/material/';


export default function Platform() {
    const router = useRouter();

    function handleSpotify() {
        signIn();
        router.push('/home');
    }

    return (
        <>
            <Head>
                <title>Select Platform</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Box>
                    <Stack spacing={2} alignItems="center">
                        <Image
                            src="/Spotify.jpg"
                            alt="Spotify Logo"
                            width="300"
                            height="150"
                            className={styles.platformImage}
                            priority
                        />
                        <Button variant="contained" onClick={handleSpotify}>
                            Connect to Spotify!
                        </Button>
                        <br />
                        <Image
                            src="/apple-music.jpg"
                            alt="Apple Music Logo"
                            width="300"
                            height="150"
                            className={styles.platformImage}
                            priority
                        />
                        <Button variant="contained" onClick={() => signIn()}>
                            Connect to Apple Music!
                        </Button>
                    </Stack>
                </Box>
            </main>
        </>
    );
}