import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/Register.module.css';
import Textbox from '@/components/Textbox';
import Button from '@/components/Button';
import { Inter } from '@next/font/google';
import { Dialog } from '@capacitor/dialog';
import { useRouter } from 'next/router';

import Password from '@/lib/passwordStrength';
import NetworkAPI from '@/lib/networkAPI';

const inter = Inter({ subsets: ['latin'] });

export default function Register() {
    const router = useRouter();

    function handleSubmit(e) {
        const form = e.target;
        const { email, username, password, confirmedPassword } = form;
        e.preventDefault();

        // Validate Fields
        if (password.value !== confirmedPassword.value) {
            Dialog.alert({
                title: 'Error',
                message: 'Passwords do not match!',
            });
            return;
        }
        if (!Password.isStrong(password.value)) {
            Dialog.alert({
                title: 'Weak Password',
                message: Password.errorMessage,
            });
            return;
        }

        // Send Request
        NetworkAPI.post('/api/users/insert', {
            email: email.value,
            username: username.value,
            password: password.value,
            confirmedPassword: confirmedPassword.value,
        })
            .then(({ data }) => {
                // TODO: Redirect to Login Page upon success
                router.push('/registerInfo');
            })
            .catch(({ status, error }) => {
                // TODO: handle error
                console.log('Error: ', status, error);
            });
    }

    return (
        <>
            <Head>
                <title>Register</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={[inter.className, styles.main].join(' ')}>
                <Image
                    className={styles.img}
                    src="/logo.png"
                    alt="Kadence Logo"
                    width={380}
                    height={200}
                    priority
                />
                <form
                    className={styles.form}
                    method="POST"
                    action="/api/users/insert"
                    onSubmit={handleSubmit}
                >
                    <Textbox
                        name="email"
                        type="email"
                        placeholder="Email"
                        required
                    />
                    <Textbox
                        name="username"
                        placeholder="Username"
                        type="text"
                        required
                    />
                    <Textbox
                        name="password"
                        placeholder="Password"
                        type="password"
                        required
                    />
                    <Textbox
                        name="confirmedPassword"
                        placeholder="Confirm Password"
                        type="password"
                        required
                    />
                    <Link className={styles.note} href="/login">
                        Already have an account? Login here!
                    </Link>
                    <Button type="submit">
                        {/* <Link href="/home">Register</Link> */}
                        Register
                    </Button>
                </form>
            </main>
        </>
    );
}
