import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/Register.module.css';
import { Button, Textbox } from '@/components/';
import { Inter } from '@next/font/google';
import { useRouter } from 'next/router';

import NetworkAPI from '@/lib/networkAPI';

const inter = Inter({ subsets: ['latin'] });

export default function Login() {
    const router = useRouter();

    async function handleSubmit(e) {
        const form = e.target;
        const { username, newPassword, newConfirmedPassword } = form;
        e.preventDefault();

        // Getting ID from the URL parameters
        const id = new URLSearchParams(window.location.search).get('id');
        console.log(id);

        // Send Request
        try {
            const data = await NetworkAPI.post('/api/users/resetPass', {
                id,
                username: username.value,
                newPassword: newPassword.value,
                newConfirmedPassword: newConfirmedPassword.value,
            });
            if (data) {
                router.push('/login');
            }
        } catch (err) {
            console.log('Error: ', err.status, err);
        }
    }

    return (
        <>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={[inter.className, styles.main].join(' ')}>
                <Image
                    className={styles.img}
                    src="/logo.png"
                    alt="Kadence Logo"
                    width={380}
                    height={200}
                    priority
                />
                <form
                    className={styles.form}
                    method="POST"
                    action="/api/users/changePass"
                    onSubmit={handleSubmit}
                >
                    <Textbox name="username" placeholder="Username" required />
                    <Textbox
                        name="newPassword"
                        placeholder="New Password"
                        type="password"
                        required
                    />
                    <Textbox
                        name="newConfirmedPassword"
                        placeholder="Confirm New Password"
                        type="password"
                        required
                    />
                    <Link className={styles.note} href="/login">
                        {"Don't mean to change passwords? Login here!"}
                    </Link>
                    <Button type="submit">Change Password</Button>
                </form>
            </main>
        </>
    );
}
