import { useSession, signIn, signOut } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import Button from '@mui/material/Button';
import { useState } from 'react';
import { Inter } from '@next/font/google';
import styles from '@/styles/Spotify.module.css';
import { BottomNav } from '@/components/';

const inter = Inter({ subsets: ['latin'] });

export default function Display() {
    const { data: session } = useSession();
    const [songName, setSongItem] = useState('');
    console.log(session);

    const getMyCurrentSong = async () => {
        const res = await fetch('/api/spotify/currentSong');
        const songItem = await res.json();
        console.log(songItem.item.name);
        setSongItem(songItem.item.name);
    };

    if (session) {
        return (
            <>
                <Head>
                    <title>Spotify Connect!</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className={[inter.className, styles.main].join(' ')}>
                    <div className={styles.header}>
                        <h1>Kadence</h1>
                    </div>
                    <Image
                        className={styles.platformImage}
                        src="/Spotify.jpg"
                        alt="Spotify Logo"
                        width={700}
                        height={350}
                        priority
                    />
                    <Button variant="contained" size="large" onClick={() => getMyCurrentSong()}>
                        Get Song!
                    </Button>
                    <h3>Your song: {songName}</h3>
                    Signed in as {session?.token?.email} <br />
                    <Button variant="contained" size="large" onClick={() => signOut()}>Sign out</Button>
                </main>
                <BottomNav name="Spotify" />
            </>
        );
    }
    return (
        <>
            <Head>
                <title>Not Logged In!</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={[inter.className, styles.main].join(' ')}>
                <div className={styles.header}>
                    <h1>Kadence</h1>
                </div>
                <Image
                    className={styles.platformImage}
                    src="/Spotify.jpg"
                    alt="Spotify Logo"
                    width={700}
                    height={350}
                    priority
                />
                <Button variant="contained" size="large" onClick={() => signIn()}>Sign In!</Button>
            </main>
            <BottomNav name="Spotify" />
        </>
    );
}
