import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Register.module.css';
import { useSession, signIn, signOut } from 'next-auth/react';

export default function SpotifyLogin() {
    const { data: session } = useSession();

    if (session) {
        return (
            <>
                Signed in as {session?.token?.email} <br />
                <button onClick={() => signOut()}>Sign out</button>
            </>
        );
    }
    return (
        <>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Image
                    className={styles.img}
                    src="/logo.png"
                    alt="Kadence Logo"
                    width={380}
                    height={200}
                    priority
                />
                <button onClick={() => signIn()}>Sign In To Spotify!</button>
            </main>
        </>
    );
}
