import { useSession, signIn, signOut } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Register.module.css';
import Button from '@/components/Button';
import { useState } from 'react';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Display() {
      return (
          <>
              <Head>
                  <title>Fitbit Connect!</title>
                  <meta
                      name="description"
                      content="Generated by create next app"
                  />
                  <meta
                      name="viewport"
                      content="width=device-width, initial-scale=1"
                  />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              <main className={[inter.className, styles.main].join(' ')}>
                  <Image
                      className={styles.img}
                      src="/logo.png"
                      alt="Kadence Logo"
                      width={380}
                      height={200}
                      priority
                  />
              </main>
          </>
      );
}